import type { Metadata } from 'next';
import { Geist, Geist_Mono, Rubik_Doodle_Shadow, Amatic_SC } from 'next/font/google';
import './globals.css';
import { GameProvider } from '../context/game-context';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

const rubikDoodleShadow = Rubik_Doodle_Shadow({
  variable: '--font-rubik-doodle-shadow',
  subsets: ['latin'],
  weight: '400'
});

const amaticSC = Amatic_SC({
  variable: '--font-amatic-sc',
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} ${rubikDoodleShadow.variable} ${amaticSC.variable} antialiased`}>
        <GameProvider>{children}</GameProvider>
      </body>
    </html>
  );
}
